### ISSUE TITLE
01.Planificación

### ISSUE THREAD

**Issue by KarinaAuday** [KarinaAuday/2023-2C-Estacionamiento#1]
**Todos los integrantes:**

- [ ] Definir que integrante es 1️⃣2️3️ y 4️⃣
Modelos
- [x] Definición de clases a crear
- [x] Repartirse las clases por integrante
Propiedades
- [ ] Definir relación y cardinalidad entre clases (idea inicial)
- [x] Definir dependencias
